### ISSUE TITLE
DEAR JACK, I AM BEGINNER, NEED MORE DETAIL FOR TO BUILD.

### ISSUE THREAD

**Issue by aulker62** [Jacksgong/android-project-combine#1]
Dear Jack.

**I really need your program**, i downloaded it and i opened with Android Studio. There are two files : 
1) Local
2) Gradle Scripts

I have 2 seperate applications in my Notebook, i made them with some helps. But i have no any idea about your program.  I am beginner, so i didn't understand, how can i use it?
Can you explain step by step please?

Many thanks for your help.

**Comment by Jacksgong** [comment]
everything has been described on [here](https://github.com/Jacksgong/android-project-combine/blob/master/README.md).

**Comment by aulker62** [comment]
Dear Jack.

Of course i read your README documents before, i watched your animated videos also.
But they can't help me. 

You said : 
Step 1. Create repos.conf File

Must i create in the LOCAL file? or in my 2 seperate application files?

I am sorry, but i am beginner.
Many thanks for your help.

**Comment by Jacksgong** [comment]
oh... sorry for my misunderstanding. before step 1:

You need clone this repo and enter the repo folder:

```shell
git clone git@github.com:Jacksgong/android-project-combine.git && cd android-project-combine
```

now you can create `repos.conf` on the repo folder.
