### ISSUE TITLE
卡死在building

### ISSUE THREAD

**Issue by chefish** [Jacksgong/android-project-combine#2]
按照教程试了一下，脚本执行完毕显示‘everything is ready, please open the combine project on AndroidStudio!’。
然后用AS打开，就卡死了
![image](https://user-images.githubusercontent.com/5964958/30062613-611cdc1a-927e-11e7-8e12-0e9fe4467533.png)

**Comment by Jacksgong** [comment]
这个估计要等等，首次Android Studio编译可能会比较久，这个不同电脑上等待的时间可能也不同。

---

如果如果等待太久，想要关闭重试可以使用以下方法:

1. `./gradlew --stop`，进入combine项目执行这个命令停止所有gradle编译。
2. 打开Activity Monitor(或Windows任务管理器）强行结束Studio
